/**
 * 币安 Alpha + Perp 联动监控看板 — 全局配置
 */

const CONFIG = {
  updateInterval: 15 * 60 * 1000, // 轮询间隔 15 分钟
  historyWindow: 60,        // 历史数据保留分钟数
  maxLogEntries: 500,       // 最大日志保留条数
  scoreWeights: {
    priceChange5m: 0.20,
    priceChange1h: 0.15,
    volumeRatio:   0.20,
    oiChange:      0.20,
    fundingAbs:    0.10,
    relativeStr:   0.15,
  },
};

const SIGNAL_THRESHOLDS = {
  spotFirst: {
    spot5mMin:  2.0,   // 现货 5m 涨幅 > 2%
    perp5mMax:  0.8,   // 合约 5m 涨幅 < 0.8%
  },
  perpFollow: {
    perp5mMin:  1.5,   // 合约 5m 涨幅 > 1.5%
    spot5mMin:  2.0,   // 现货 5m 涨幅 > 2%（已先动）
    spot1hMin:  3.0,   // 现货 1h 涨幅 > 3%
  },
  oiPileUp: {
    oiChangeMin:    5.0,  // OI 变化 > 5%
    priceChangeMax: 1.0,  // 价格变化 < 1%（价格平稳但 OI 堆积）
  },
  crowdedRisk: {
    fundingMin:  0.05,   // funding rate > 0.05%
    oiChangeMin: 8.0,    // OI 变化 > 8%
  },
  shortSqueeze: {
    priceRiseMin:  2.0,  // 价格上涨 > 2%
    oiDropMax:    -3.0,  // OI 下降 > 3%（空头平仓）
  },
  watching: {
    anyChangeMin: 1.0,   // 任何维度出现 > 1% 变化即进入观察
  },
};

const COIN_POOL = [
  {
    symbol: 'ZRC',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ZRCUSDT',
    perpContract: 'ZRCUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'ZKJ',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ZKJUSDT',
    perpContract: 'ZKJUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'YALA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'YALAUSDT',
    perpContract: 'YALAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'XPIN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'XPINUSDT',
    perpContract: 'XPINUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'XNY',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'XNYUSDT',
    perpContract: 'XNYUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'XAN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'XANUSDT',
    perpContract: 'XANUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'VELVET',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'VELVETUSDT',
    perpContract: 'VELVETUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'USELESS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'USELESSUSDT',
    perpContract: 'USELESSUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'UB',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'UBUSDT',
    perpContract: 'UBUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'UAI',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'UAIUSDT',
    perpContract: 'UAIUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'TRADOOR',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TRADOORUSDT',
    perpContract: 'TRADOORUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'TOSHI',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TOSHIUSDT',
    perpContract: 'TOSHIUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'TAKE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TAKEUSDT',
    perpContract: 'TAKEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'TAIKO',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TAIKOUSDT',
    perpContract: 'TAIKOUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'TAG',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TAGUSDT',
    perpContract: 'TAGUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'TAC',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TACUSDT',
    perpContract: 'TACUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'TA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'TAUSDT',
    perpContract: 'TAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'STBL',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'STBLUSDT',
    perpContract: 'STBLUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'STABLE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'STABLEUSDT',
    perpContract: 'STABLEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'SQD',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'SQDUSDT',
    perpContract: 'SQDUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'SOON',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'SOONUSDT',
    perpContract: 'SOONUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'SKYAI',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'SKYAIUSDT',
    perpContract: 'SKYAIUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: 'SIREN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'SIRENUSDT',
    perpContract: 'SIRENUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'RVV',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'RVVUSDT',
    perpContract: 'RVVUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'RLS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'RLSUSDT',
    perpContract: 'RLSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'RIVER',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'RIVERUSDT',
    perpContract: 'RIVERUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'RAVE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'RAVEUSDT',
    perpContract: 'RAVEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'Q',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'QUSDT',
    perpContract: 'QUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'PUMPBTC',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'PUMPBTCUSDT',
    perpContract: 'PUMPBTCUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'PUFFER',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'PUFFERUSDT',
    perpContract: 'PUFFERUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'PTB',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'PTBUSDT',
    perpContract: 'PTBUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'POWER',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'POWERUSDT',
    perpContract: 'POWERUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'PLAY',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'PLAYUSDT',
    perpContract: 'PLAYUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'PIEVERSE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'PIEVERSEUSDT',
    perpContract: 'PIEVERSEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'ORDER',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ORDERUSDT',
    perpContract: 'ORDERUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'ON',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ONUSDT',
    perpContract: 'ONUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'OL',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'OLUSDT',
    perpContract: 'OLUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'NIGHT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'NIGHTUSDT',
    perpContract: 'NIGHTUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'NAORIS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'NAORISUSDT',
    perpContract: 'NAORISUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'MYX',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'MYXUSDT',
    perpContract: 'MYXUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'MERL',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'MERLUSDT',
    perpContract: 'MERLUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'M',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'MUSDT',
    perpContract: 'MUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'LYN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'LYNUSDT',
    perpContract: 'LYNUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'LIGHT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'LIGHTUSDT',
    perpContract: 'LIGHTUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'LAB',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'LABUSDT',
    perpContract: 'LABUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'KOMA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'KOMAUSDT',
    perpContract: 'KOMAUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '高波动'],
  },
  {
    symbol: 'KGEN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'KGENUSDT',
    perpContract: 'KGENUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'JCT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'JCTUSDT',
    perpContract: 'JCTUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'IRYS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'IRYSUSDT',
    perpContract: 'IRYSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'IR',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'IRUSDT',
    perpContract: 'IRUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'IN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'INUSDT',
    perpContract: 'INUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'IDOL',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'IDOLUSDT',
    perpContract: 'IDOLUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'HANA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'HANAUSDT',
    perpContract: 'HANAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'H',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'HUSDT',
    perpContract: 'HUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'GUA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'GUAUSDT',
    perpContract: 'GUAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'FOLKS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'FOLKSUSDT',
    perpContract: 'FOLKSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'FHE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'FHEUSDT',
    perpContract: 'FHEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'EVAA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'EVAAUSDT',
    perpContract: 'EVAAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'ESPORTS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ESPORTSUSDT',
    perpContract: 'ESPORTSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'EPT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'EPTUSDT',
    perpContract: 'EPTUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'DOOD',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'DOODUSDT',
    perpContract: 'DOODUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'DAM',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'DAMUSDT',
    perpContract: 'DAMUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'CYS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'CYSUSDT',
    perpContract: 'CYSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'CUDIS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'CUDISUSDT',
    perpContract: 'CUDISUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'CROSS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'CROSSUSDT',
    perpContract: 'CROSSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'COMMON',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'COMMONUSDT',
    perpContract: 'COMMONUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'COLLECT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'COLLECTUSDT',
    perpContract: 'COLLECTUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'COAI',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'COAIUSDT',
    perpContract: 'COAIUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: 'CLO',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'CLOUSDT',
    perpContract: 'CLOUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'CARV',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'CARVUSDT',
    perpContract: 'CARVUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', '重点观察'],
  },
  {
    symbol: 'BTR',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BTRUSDT',
    perpContract: 'BTRUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BR',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BRUSDT',
    perpContract: 'BRUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BOB',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BOBUSDT',
    perpContract: 'BOBUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BLUAI',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BLUAIUSDT',
    perpContract: 'BLUAIUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: 'BLESS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BLESSUSDT',
    perpContract: 'BLESSUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BID',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BIDUSDT',
    perpContract: 'BIDUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BEAT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BEATUSDT',
    perpContract: 'BEATUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BDXN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BDXNUSDT',
    perpContract: 'BDXNUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'BAS',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BASUSDT',
    perpContract: 'BASUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'B2',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'B2USDT',
    perpContract: 'B2USDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'B',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'BUSDT',
    perpContract: 'BUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'ARIA',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'ARIAUSDT',
    perpContract: 'ARIAUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'APR',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'APRUSDT',
    perpContract: 'APRUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'AKE',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'AKEUSDT',
    perpContract: 'AKEUSDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: 'AIOT',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'AIOTUSDT',
    perpContract: 'AIOTUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: 'AIO',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'AIOUSDT',
    perpContract: 'AIOUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: 'AIN',
    isAlpha: true,
    hasPerp: true,
    alphaPair: 'AINUSDT',
    perpContract: 'AINUSDT',
    isPriority: true,
    tags: ['Alpha+Perp', 'AI概念'],
  },
  {
    symbol: '42',
    isAlpha: true,
    hasPerp: true,
    alphaPair: '42USDT',
    perpContract: '42USDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
  {
    symbol: '4',
    isAlpha: true,
    hasPerp: true,
    alphaPair: '4USDT',
    perpContract: '4USDT',
    isPriority: false,
    tags: ['Alpha+Perp'],
  },
];
